apiVersion: v1
kind: Secret
metadata:
  name: llm-metrics
  namespace: 3scale
  labels:
    apimanager.apps.3scale.net/watched-by: apimanager
type: Opaque
data:
  apicast-policy.json: "$(cat ./apicast-policy.json | base64)"
  custom_metrics.lua: "$(cat ./custom_metrics.lua | base64)"
  init.lua: "$(cat ./init.lua | base64)"
  llm.lua: "$(cat ./llm.lua | base64)"
  portal_client.lua: "$(cat ./portal_client.lua | base64)"
  response.lua: "$(cat ./response.lua | base64)"