apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
spec:
  name: ocs-storagecluster
  namespace: openshift-storage
  kind: storagecluster.ocs.openshift.io/v1