apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  namespace: 3scale
spec:
  wildcardDomain: apps.cluster-7tqcw.7tqcw.sandbox3194.opentlc.com # Change this to your wildcard domain
  resourceRequirementsEnabled: false
  tenantName: maas
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: ocs-storagecluster-cephfs
  apicast:
    stagingSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
             name: llm-metrics
    productionSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
             name: llm-metrics